# =============================================================================
# IRI MANUSCRIPT - UNIFIED COLOR SCHEME FIGURES
# =============================================================================
# Professional medical journal color palette: Teal/Green-based monochromatic
# All 3 figures with consistent styling
# =============================================================================

library(ggplot2)
library(dplyr)
library(tidyr)

# =============================================================================
# COLOR PALETTE: IRI STUDY (Teal/Green Monochromatic)
# =============================================================================
# Distinct from RIR (navy blue), professional for medical journals
iri_colors <- list(
  # For quartiles Q1 (worst) to Q4 (best) - gradient from dark to light
  q1 = "#1B5E5E",      # Dark teal (lowest resilience)
  q2 = "#2E8B8B",      # Medium-dark teal
  q3 = "#5CACAC",      # Medium teal
  q4 = "#8FCFCF",      # Light teal (highest resilience)
  
  # For binary significant/not
  significant = "#1B5E5E",   # Dark teal
  nonsignificant = "#9E9E9E", # Gray
  
  # Reference line
  reference = "#6B6B6B"
)

# =============================================================================
# PUBLICATION THEME
# =============================================================================
theme_iri <- function(base_size = 11) {
  theme_minimal(base_size = base_size) +
    theme(
      text = element_text(color = "black"),
      plot.title = element_text(size = base_size + 1, face = "bold", hjust = 0),
      plot.subtitle = element_text(size = base_size - 1, color = "gray40", hjust = 0),
      plot.caption = element_text(size = base_size - 2, color = "gray50", hjust = 0),
      axis.title = element_text(size = base_size, face = "bold"),
      axis.text = element_text(size = base_size - 1, color = "black"),
      axis.line = element_line(color = "black", linewidth = 0.4),
      axis.ticks = element_line(color = "black", linewidth = 0.3),
      legend.position = "bottom",
      legend.title = element_text(size = base_size - 1, face = "bold"),
      legend.text = element_text(size = base_size - 1),
      legend.background = element_blank(),
      legend.key = element_blank(),
      panel.grid.major.y = element_line(color = "gray90", linewidth = 0.3),
      panel.grid.major.x = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "white", color = NA),
      plot.background = element_rect(fill = "white", color = NA),
      plot.margin = margin(15, 15, 15, 15),
      strip.text = element_text(face = "bold", size = base_size)
    )
}

# Output paths (relative to script location)
script_dir <- tryCatch(dirname(sys.frame(1)$ofile), error = function(e) ".")
project_root <- normalizePath(file.path(script_dir, ".."), mustWork = FALSE)
if (!dir.exists(file.path(project_root, "output"))) {
  project_root <- normalizePath(file.path(getwd(), ".."), mustWork = FALSE)
}
output_dir <- file.path(project_root, "output")
manuscript_dir <- file.path(project_root, "manuscript", "figures")
dir.create(manuscript_dir, recursive = TRUE, showWarnings = FALSE)

# ============================================================================
# FIGURE 3: FOREST PLOT - IRI AND FUNCTIONAL OUTCOMES
# ============================================================================
cat("[Figure 3: Forest Plot]\n")

# Read results from analysis output (generated by 05_functional_analysis.R)
results_file <- file.path(output_dir, "functional_outcomes_results.csv")
if (file.exists(results_file)) {
  results_raw <- read.csv(results_file)
  results <- data.frame(
    Outcome = results_raw$Outcome,
    OR = results_raw$OR_Q1vsQ4,
    CI_low = results_raw$CI_low_Q1,
    CI_high = results_raw$CI_high_Q1,
    p = results_raw$p_Q1vsQ4,
    significant = results_raw$p_Q1vsQ4 < 0.05
  )
  # Clean outcome labels for plot
  results$Outcome <- c("Fair/Poor Self-Rated Health", "Difficulty Walking", "Depression (PHQ-9 >=10)")
  cat("  Loaded Q1 vs Q4 results dynamically from", results_file, "\n")
} else {
  stop("functional_outcomes_results.csv not found. Run 05_functional_analysis.R first.")
}

results$Outcome <- factor(results$Outcome, levels = rev(results$Outcome))
results$OR_label <- sprintf("%.2f (%.2f-%.2f)", results$OR, results$CI_low, results$CI_high)

p1 <- ggplot(results, aes(x = OR, y = Outcome)) +
  geom_vline(xintercept = 1, linetype = "dashed", color = iri_colors$reference, linewidth = 0.6) +
  geom_errorbarh(aes(xmin = CI_low, xmax = CI_high), height = 0.15, linewidth = 0.8, color = "gray30") +
  geom_point(aes(color = significant), size = 4.5) +
  geom_text(aes(label = OR_label, x = CI_high + 0.8), hjust = 0, size = 3.2) +
  scale_color_manual(values = c("TRUE" = iri_colors$significant, "FALSE" = iri_colors$nonsignificant), 
                     guide = "none") +
  scale_x_log10(breaks = c(0.5, 1, 2, 4), limits = c(0.4, 8)) +
  labs(
    title = "Lowest IRI Quartile (Q1) vs Highest (Q4) and Functional Outcomes",
    subtitle = "NHANES 2015-2016 | Adjusted for age, sex, and race/ethnicity",
    x = "Odds Ratio (95% CI)",
    y = ""
  ) +
  theme_iri() +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.y = element_text(size = 11)
  )

ggsave(file.path(output_dir, "figure3_forest_plot.png"), p1, width = 9, height = 4, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "figure3_forest_plot.pdf"), p1, width = 9, height = 4, bg = "white")
ggsave(file.path(manuscript_dir, "figure3_forest_plot.png"), p1, width = 9, height = 4, dpi = 300, bg = "white")
ggsave(file.path(manuscript_dir, "figure3_forest_plot.pdf"), p1, width = 9, height = 4, bg = "white")
cat("  Saved Figure 1\n")

# ============================================================================
# FIGURE 2: PREVALENCE BY IRI QUARTILE
# ============================================================================
cat("\n[Figure 2: Prevalence by Quartile]\n")

# Compute survey-weighted prevalence by IRI quartile from cohort data
prev_csv <- file.path(project_root, "data", "processed", "iri_functional_cohort.csv")
if (file.exists(prev_csv)) {
  library(survey)
  options(survey.lonely.psu = "adjust")
  prev_df <- read.csv(prev_csv)
  prev_df <- prev_df %>%
    filter(iri_quartile %in% c("Q1", "Q2", "Q3", "Q4")) %>%
    mutate(iri_quartile = factor(iri_quartile, levels = c("Q1", "Q2", "Q3", "Q4")))

  n_cycles <- 1  # DEXA only available in 2015-2016 (single cycle)
  prev_design <- svydesign(
    id = ~psu, strata = ~strata,
    weights = ~ I(mec_weight / n_cycles),
    data = prev_df %>% filter(!is.na(mec_weight), !is.na(psu), !is.na(strata)),
    nest = TRUE
  )

  outcomes <- c("poor_health", "difficulty_walking", "depression")
  outcome_labels <- c("Fair/Poor Health", "Difficulty Walking", "Depression")
  prev_rows <- list()
  for (i in seq_along(outcomes)) {
    for (q in c("Q1", "Q2", "Q3", "Q4")) {
      sub_svy <- subset(prev_design, iri_quartile == q)
      fml <- as.formula(paste0("~", outcomes[i]))
      est <- tryCatch(svymean(fml, sub_svy, na.rm = TRUE), error = function(e) NULL)
      q_label <- if (q == "Q1") "Q1\n(Lowest)" else if (q == "Q4") "Q4\n(Highest)" else q
      prev_rows[[length(prev_rows) + 1]] <- data.frame(
        Quartile = q_label,
        Outcome = outcome_labels[i],
        Prevalence = if (!is.null(est)) as.numeric(est) * 100 else NA,
        SE = if (!is.null(est)) as.numeric(SE(est)) * 100 else NA
      )
    }
  }
  prev_data <- do.call(rbind, prev_rows)
  cat("  Computed survey-weighted prevalence from cohort data\n")
} else {
  stop("iri_functional_cohort.csv not found. Run 02_build_cohort.py first.")
}

prev_data$Quartile <- factor(prev_data$Quartile, levels = c("Q1\n(Lowest)", "Q2", "Q3", "Q4\n(Highest)"))
prev_data$Outcome <- factor(prev_data$Outcome, levels = c("Fair/Poor Health", "Difficulty Walking", "Depression"))

# Map quartile to color
quartile_colors <- c("Q1\n(Lowest)" = iri_colors$q1, "Q2" = iri_colors$q2, 
                     "Q3" = iri_colors$q3, "Q4\n(Highest)" = iri_colors$q4)

p2 <- ggplot(prev_data, aes(x = Quartile, y = Prevalence, fill = Quartile)) +
  geom_bar(stat = "identity", width = 0.7) +
  geom_errorbar(aes(ymin = pmax(0, Prevalence - 1.96*SE), ymax = Prevalence + 1.96*SE), 
                width = 0.2, linewidth = 0.5) +
  facet_wrap(~Outcome, scales = "free_y", ncol = 3) +
  scale_fill_manual(values = quartile_colors, guide = "none") +
  labs(
    title = "Functional Outcome Prevalence by IRI Quartile",
    subtitle = "Survey-weighted estimates | NHANES 2015-2016",
    x = "IRI Quartile",
    y = "Prevalence (%)",
    caption = "Error bars represent 95% CI. Lower quartiles indicate lower inflammatory resilience."
  ) +
  theme_iri()

ggsave(file.path(output_dir, "figure2_prevalence_by_quartile.png"), p2, width = 10, height = 4.5, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "figure2_prevalence_by_quartile.pdf"), p2, width = 10, height = 4.5, bg = "white")
ggsave(file.path(manuscript_dir, "figure2_prevalence_by_quartile.png"), p2, width = 10, height = 4.5, dpi = 300, bg = "white")
ggsave(file.path(manuscript_dir, "figure2_prevalence_by_quartile.pdf"), p2, width = 10, height = 4.5, bg = "white")
cat("  Saved Figure 2\n")

# ============================================================================
# FIGURE 1: IRI COMPONENTS BY QUARTILE
# ============================================================================
cat("\n[Figure 1: IRI Components]\n")

data_path <- file.path(project_root, "data", "processed", "iri_functional_cohort.csv")
dat <- read.csv(data_path)

component_summary <- dat %>%
  group_by(iri_quartile) %>%
  summarise(
    CRP = mean(hscrp, na.rm = TRUE),
    Albumin = mean(albumin, na.rm = TRUE),
    ALMI_z = mean(z_almi, na.rm = TRUE),
    .groups = "drop"
  )

comp_long <- pivot_longer(component_summary, cols = c(CRP, Albumin, ALMI_z), 
                          names_to = "Component", values_to = "Value") %>%
  mutate(
    Component = factor(Component, levels = c("CRP", "Albumin", "ALMI_z"),
                       labels = c("hs-CRP (mg/L)", "Albumin (g/dL)", "ALMI (z-score)"))
  )

# Map quartile to color (Q1-Q4)
comp_long$iri_quartile <- factor(comp_long$iri_quartile, levels = c("Q1", "Q2", "Q3", "Q4"))
quartile_colors_short <- c("Q1" = iri_colors$q1, "Q2" = iri_colors$q2, 
                           "Q3" = iri_colors$q3, "Q4" = iri_colors$q4)

p3 <- ggplot(comp_long, aes(x = iri_quartile, y = Value, fill = iri_quartile)) +
  geom_bar(stat = "identity", width = 0.7) +
  facet_wrap(~Component, scales = "free_y", ncol = 3) +
  scale_fill_manual(values = quartile_colors_short, name = "IRI Quartile") +
  labs(
    title = "IRI Component Values by Quartile",
    subtitle = "Lower hs-CRP, higher albumin, and higher ALMI indicate better resilience",
    x = "IRI Quartile",
    y = "Mean Value",
    caption = "Q1 = lowest resilience (highest inflammation, lowest muscle mass); Q4 = highest resilience"
  ) +
  theme_iri() +
  theme(legend.position = "none")

ggsave(file.path(output_dir, "figure1_iri_components.png"), p3, width = 10, height = 4.5, dpi = 300, bg = "white")
ggsave(file.path(output_dir, "figure1_iri_components.pdf"), p3, width = 10, height = 4.5, bg = "white")
ggsave(file.path(manuscript_dir, "figure1_iri_components.png"), p3, width = 10, height = 4.5, dpi = 300, bg = "white")
ggsave(file.path(manuscript_dir, "figure1_iri_components.pdf"), p3, width = 10, height = 4.5, bg = "white")
cat("  Saved Figure 3\n")

# ============================================================================
# COMPLETE
# ============================================================================
cat("\n", strrep("=", 60), "\n")
cat("IRI FIGURES COMPLETE - UNIFIED TEAL COLOR SCHEME\n")
cat(strrep("=", 60), "\n")
cat("\nColor palette:\n")
cat("  Q1 (dark):  ", iri_colors$q1, "\n")
cat("  Q2:         ", iri_colors$q2, "\n")
cat("  Q3:         ", iri_colors$q3, "\n")
cat("  Q4 (light): ", iri_colors$q4, "\n")
cat("\nAll 3 figures saved to:", output_dir, "\n")
cat("Also copied to:", manuscript_dir, "\n")
