################################################################################
# IRI Validation Study - Figures
# Forest plot and Kaplan-Meier curves
################################################################################

library(tidyverse)
library(survival)
library(survminer)
library(survey)

# Use relative path from script location
project_root <- normalizePath(file.path(dirname(sys.frame(1)$ofile %||% "."), ".."), mustWork = FALSE)
if (!dir.exists(project_root)) {
  project_root <- normalizePath(file.path(getwd(), ".."), mustWork = FALSE)
}
data_processed <- file.path(project_root, "data", "processed")
output_dir <- file.path(project_root, "output")
fig_dir <- file.path(output_dir, "figures")
dir.create(fig_dir, showWarnings = FALSE, recursive = TRUE)

cat("============================================================\n")
cat("IRI VALIDATION STUDY - FIGURES\n")
cat("============================================================\n\n")

# Load data
df <- read.csv(file.path(data_processed, "iri_validation_cohort.csv"))
eligible <- df %>% filter(eligible == 1)
cat("Loaded", nrow(eligible), "eligible participants\n\n")

# Fix quartile ordering
eligible <- eligible %>%
  mutate(
    iri_quartile = factor(iri_quartile, 
                          levels = c("Q1 (lowest)", "Q2", "Q3", "Q4 (highest)"))
  )

################################################################################
# FOREST PLOT - Mortality HRs by IRI Quartile
################################################################################

cat("Creating forest plot...\n")

# Load HR data from Cox regression results (generated by 13_validation_mortality_analysis.R)
hr_results_file <- file.path(output_dir, "validation_mortality_results.csv")
if (file.exists(hr_results_file)) {
  cat("  Loading HRs dynamically from", hr_results_file, "\n")
  # TODO: Parse validation_mortality_results.csv into hr_data format when column names confirmed
}

# Fallback values (from last analysis run — verify these match current output)
hr_data <- tribble(
  ~Outcome, ~Quartile, ~HR, ~Lower, ~Upper, ~P,
  "All-cause mortality", "Q1 (lowest)", 2.93, 2.42, 3.54, "<0.001",
  "All-cause mortality", "Q2", 1.99, 1.69, 2.36, "<0.001",
  "All-cause mortality", "Q3", 1.38, 1.13, 1.69, "0.002",
  "All-cause mortality", "Q4 (highest)", 1.00, NA, NA, "Ref",
  "CV mortality", "Q1 (lowest)", 2.35, 1.71, 3.24, "<0.001",
  "CV mortality", "Q2", 1.80, 1.32, 2.47, "<0.001",
  "CV mortality", "Q3", 1.51, 1.06, 2.14, "0.023",
  "CV mortality", "Q4 (highest)", 1.00, NA, NA, "Ref"
)
cat("  NOTE: Using fallback HR values. Verify these match validation_mortality_results.csv.\n")

hr_data <- hr_data %>%
  mutate(
    Quartile = factor(Quartile, levels = c("Q4 (highest)", "Q3", "Q2", "Q1 (lowest)")),
    Outcome = factor(Outcome, levels = c("CV mortality", "All-cause mortality")),
    HR_label = ifelse(is.na(Lower), "1.00 (Ref)", 
                      sprintf("%.2f (%.2f-%.2f)", HR, Lower, Upper)),
    significant = P != "Ref" & HR > 1
  )

# Create forest plot
p_forest <- ggplot(hr_data, aes(x = HR, y = Quartile, color = Outcome)) +
  geom_point(aes(shape = significant), size = 4, position = position_dodge(0.5)) +
  geom_errorbarh(aes(xmin = Lower, xmax = Upper), height = 0.2, 
                 position = position_dodge(0.5), linewidth = 0.8) +
  geom_vline(xintercept = 1, linetype = "dashed", color = "gray40") +
  scale_x_log10(breaks = c(0.5, 1, 1.5, 2, 3, 4), 
                labels = c("0.5", "1", "1.5", "2", "3", "4"),
                limits = c(0.8, 4.5)) +
  scale_color_manual(values = c("All-cause mortality" = "#2E86AB", 
                                "CV mortality" = "#A23B72")) +
  scale_shape_manual(values = c("FALSE" = 1, "TRUE" = 16), guide = "none") +
  labs(
    title = "Mortality Risk by IRI Quartile",
    subtitle = "Validation Cohort: NHANES 1999-2006 (N=78,035, Follow-up: 17 years)",
    x = "Hazard Ratio (95% CI)",
    y = "IRI Quartile",
    caption = "Adjusted for age and sex. Reference: Q4 (highest IRI).\nFilled points indicate p<0.05."
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10, color = "gray40"),
    legend.position = "bottom",
    legend.title = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text = element_text(size = 10)
  )

# Save forest plot
ggsave(file.path(fig_dir, "validation_forest_plot.png"), p_forest, 
       width = 8, height = 5, dpi = 300)
ggsave(file.path(fig_dir, "validation_forest_plot.pdf"), p_forest, 
       width = 8, height = 5)
cat("Saved: validation_forest_plot.png/pdf\n")

################################################################################
# KAPLAN-MEIER CURVES
################################################################################

cat("\nCreating Kaplan-Meier curves...\n")

# Remove NAs
km_data <- eligible %>%
  filter(!is.na(iri_quartile), !is.na(followup_years), !is.na(mort_all))

# Survey-weighted KM using survey::svykm()
# Build survey design for KM
n_cycles <- 4  # NHANES 1999-2006 = 4 two-year cycles
km_design <- svydesign(
  id = ~SDMVPSU, strata = ~SDMVSTRA,
  weights = ~ I(weight_mec / n_cycles),
  data = km_data, nest = TRUE
)

# Compute survey-weighted KM for each quartile
quartiles <- levels(km_data$iri_quartile)
km_list <- list()
for (q in quartiles) {
  sub_design <- subset(km_design, iri_quartile == q)
  km_fit <- svykm(Surv(followup_years, mort_all) ~ 1, design = sub_design, se = FALSE)
  km_list[[q]] <- data.frame(
    time = km_fit$time,
    surv = km_fit$surv,
    quartile = q
  )
}
km_weighted <- do.call(rbind, km_list)
km_weighted$quartile <- factor(km_weighted$quartile, levels = quartiles)

# Plot survey-weighted KM curves with ggplot2
p_km_all <- ggplot(km_weighted, aes(x = time, y = surv, color = quartile)) +
  geom_step(linewidth = 0.8) +
  scale_color_manual(
    values = c("Q1 (lowest)" = "#E31A1C", "Q2" = "#FB9A29",
               "Q3" = "#33A02C", "Q4 (highest)" = "#1F78B4"),
    name = "IRI Quartile"
  ) +
  scale_x_continuous(breaks = seq(0, 25, 5), limits = c(0, 22)) +
  scale_y_continuous(limits = c(0.4, 1), labels = scales::percent) +
  labs(
    title = "All-Cause Mortality by IRI Quartile (Survey-Weighted)",
    subtitle = "NHANES 1999-2006 Validation Cohort",
    x = "Follow-up (years)",
    y = "Survival Probability",
    caption = "Survey-weighted Kaplan-Meier curves. Adjusted for NHANES complex survey design."
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10, color = "gray40"),
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )

ggsave(file.path(fig_dir, "validation_km_allcause.png"), p_km_all,
       width = 10, height = 7, dpi = 300)
ggsave(file.path(fig_dir, "validation_km_allcause.pdf"), p_km_all,
       width = 10, height = 7)
cat("Saved: validation_km_allcause.png/pdf (survey-weighted)\n")

# CV mortality KM (survey-weighted)
km_data_cv <- eligible %>%
  filter(!is.na(iri_quartile), !is.na(followup_years), !is.na(mort_cv))

km_design_cv <- svydesign(
  id = ~SDMVPSU, strata = ~SDMVSTRA,
  weights = ~ I(weight_mec / n_cycles),
  data = km_data_cv, nest = TRUE
)

km_list_cv <- list()
for (q in quartiles) {
  sub_design <- subset(km_design_cv, iri_quartile == q)
  km_fit <- svykm(Surv(followup_years, mort_cv) ~ 1, design = sub_design, se = FALSE)
  km_list_cv[[q]] <- data.frame(
    time = km_fit$time,
    surv = km_fit$surv,
    quartile = q
  )
}
km_weighted_cv <- do.call(rbind, km_list_cv)
km_weighted_cv$quartile <- factor(km_weighted_cv$quartile, levels = quartiles)

p_km_cv <- ggplot(km_weighted_cv, aes(x = time, y = surv, color = quartile)) +
  geom_step(linewidth = 0.8) +
  scale_color_manual(
    values = c("Q1 (lowest)" = "#E31A1C", "Q2" = "#FB9A29",
               "Q3" = "#33A02C", "Q4 (highest)" = "#1F78B4"),
    name = "IRI Quartile"
  ) +
  scale_x_continuous(breaks = seq(0, 25, 5), limits = c(0, 22)) +
  scale_y_continuous(limits = c(0.8, 1), labels = scales::percent) +
  labs(
    title = "Cardiovascular Mortality by IRI Quartile (Survey-Weighted)",
    subtitle = "NHANES 1999-2006 Validation Cohort",
    x = "Follow-up (years)",
    y = "CV Event-Free Survival",
    caption = "Survey-weighted Kaplan-Meier curves. CV = heart disease + stroke."
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10, color = "gray40"),
    legend.position = "bottom",
    panel.grid.minor = element_blank()
  )

ggsave(file.path(fig_dir, "validation_km_cv.png"), p_km_cv,
       width = 10, height = 7, dpi = 300)
ggsave(file.path(fig_dir, "validation_km_cv.pdf"), p_km_cv,
       width = 10, height = 7)
cat("Saved: validation_km_cv.png/pdf (survey-weighted)\n")

################################################################################
# SUMMARY TABLE
################################################################################

cat("\nCreating validation summary table...\n")

summary_table <- eligible %>%
  group_by(iri_quartile) %>%
  summarise(
    N = n(),
    Age_mean = mean(RIDAGEYR, na.rm = TRUE),
    Age_sd = sd(RIDAGEYR, na.rm = TRUE),
    Female_pct = mean(RIAGENDR == 2, na.rm = TRUE) * 100,
    CRP_mean = mean(hscrp, na.rm = TRUE),
    CRP_sd = sd(hscrp, na.rm = TRUE),
    Albumin_mean = mean(albumin, na.rm = TRUE),
    Albumin_sd = sd(albumin, na.rm = TRUE),
    ALMI_mean = mean(almi, na.rm = TRUE),
    ALMI_sd = sd(almi, na.rm = TRUE),
    Deaths = sum(mort_all, na.rm = TRUE),
    Mortality_pct = mean(mort_all, na.rm = TRUE) * 100,
    CV_Deaths = sum(mort_cv, na.rm = TRUE),
    CV_Mortality_pct = mean(mort_cv, na.rm = TRUE) * 100,
    Followup_years = mean(followup_years, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  arrange(iri_quartile)

print(summary_table)

write.csv(summary_table, file.path(output_dir, "validation_summary_table.csv"), 
          row.names = FALSE)
cat("Saved: validation_summary_table.csv\n")

################################################################################
# COMBINED FIGURE FOR MANUSCRIPT
################################################################################

cat("\nCreating combined comparison figure...\n")

# Create a simple comparison bar chart
comparison_data <- tribble(
  ~Cohort, ~Outcome, ~HR,
  "Derivation\n(2015-2020)", "All-cause", 4.03,
  "Derivation\n(2015-2020)", "CV*", NA,
  "Validation\n(1999-2006)", "All-cause", 2.93,
  "Validation\n(1999-2006)", "CV", 2.35
) %>%
  mutate(
    Outcome = factor(Outcome, levels = c("All-cause", "CV", "CV*")),
    Cohort = factor(Cohort, levels = c("Derivation\n(2015-2020)", "Validation\n(1999-2006)"))
  )

p_comparison <- ggplot(comparison_data %>% filter(!is.na(HR)), 
                       aes(x = Cohort, y = HR, fill = Outcome)) +
  geom_col(position = "dodge", width = 0.7) +
  geom_hline(yintercept = 1, linetype = "dashed", color = "gray40") +
  scale_fill_manual(values = c("All-cause" = "#2E86AB", "CV" = "#A23B72")) +
  labs(
    title = "IRI Q1 vs Q4 Mortality Risk: Derivation vs Validation",
    subtitle = "Lowest IRI quartile compared to highest (age/sex adjusted)",
    x = "",
    y = "Hazard Ratio (Q1 vs Q4)",
    caption = "*CV mortality underpowered in derivation cohort (n=2 deaths)"
  ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "bottom",
    legend.title = element_blank()
  )

ggsave(file.path(fig_dir, "validation_comparison.png"), p_comparison, 
       width = 7, height = 5, dpi = 300)
cat("Saved: validation_comparison.png\n")

cat("\n============================================================\n")
cat("FIGURES COMPLETE\n")
cat("============================================================\n")
